name: Bug Report
description: create a report to help us improve
title: "Bug Report: "
labels: [bug]
assignees:
  - bloomkd46
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: "Describe The Bug:"
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
      
  - type: textarea
    id: how-happend
    attributes:
      label: "To Reproduce:"
      placeholder: Steps to reproduce the behavior.
    validations:
      required: true
            
  - type: textarea
    id: should-happend
    attributes:
      label: "Expected behavior:"
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: "Log Ouput:"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Show the Minecraft logs here if possible. Replace any sensitive information with *'s.
      render: shell
    validations:
      required: false
            