name: Support Request
description: Need Help?
title: "Support Request: "
labels: "question, help wanted"
assignees:
  - bloomkd46
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Support Request!
        
  - type: textarea
    id: what-happened
    attributes:
      label: "Describe Your Problem:"
      placeholder: A clear and concise description of what your problem is.
    validations:
      required: true
            
  - type: textarea
    id: should-happend
    attributes:
      label: "Expected behavior:"
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: "Log Ouput:"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Show the Minecraft logs here if possible. Replace any sensitive information with *'s'.
      render: shell
    validations:
      required: false
